version: '3.8'

services:
  mongodb-prod:
    image: mongo
    restart: always
    volumes:
      - db-data-prod:/data/db
    ports:
      - 27027:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: asdf

  mongo-express-prod:
    image: mongo-express
    restart: always
    depends_on:
      - mongodb-prod
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb-prod
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: asdf
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123

  # redis1:
  #   container_name: redis1
  #   image: redis
  #   command: redis-server --requirepass asdf
  #   ports:
  #   - '6379:6379'

  app-prod:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: sh -c "npm install && npm run start:prod"
    restart: always
    ports:
      - 8090:8080
    working_dir: /app
    depends_on:
      - mongodb-prod
    environment:
      - VIRTUAL_HOST=prod.silver-tercel.com
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=prod.silver-tercel.com
      - LETSENCRYPT_EMAIL=steedude@gmail.com

volumes:
  db-data-prod:
